name: scale_factor
description: Scale Factor is simple tool for converting pixel values between densities supported by android and iOS devices.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

#  assets:
#    - assets/

  fonts:
  - family: RedHatText
    fonts:
    - asset: fonts/RedHatText-Regular.ttf
    - asset: fonts/RedHatText-Medium.ttf
      weight: 500
    - asset: fonts/RedHatText-Bold.ttf
      weight: 900

  - family: CustomIcons
    fonts:
      - asset: icons/CustomIcons.ttf